// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kastore_version
Rcpp::IntegerVector kastore_version();
RcppExport SEXP _tskitr_kastore_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(kastore_version());
    return rcpp_result_gen;
END_RCPP
}
// tskit_version
Rcpp::IntegerVector tskit_version();
RcppExport SEXP _tskitr_tskit_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tskit_version());
    return rcpp_result_gen;
END_RCPP
}
// ts_load
SEXP ts_load(std::string file, int options);
RcppExport SEXP _tskitr_ts_load(SEXP fileSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_load(file, options));
    return rcpp_result_gen;
END_RCPP
}
// ts_dump
void ts_dump(SEXP ts, std::string file, int options);
RcppExport SEXP _tskitr_ts_dump(SEXP tsSEXP, SEXP fileSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< int >::type options(optionsSEXP);
    ts_dump(ts, file, options);
    return R_NilValue;
END_RCPP
}
// ts_num
Rcpp::List ts_num(SEXP ts);
RcppExport SEXP _tskitr_ts_num(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_provenances
int ts_num_provenances(SEXP ts);
RcppExport SEXP _tskitr_ts_num_provenances(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_provenances(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_populations
int ts_num_populations(SEXP ts);
RcppExport SEXP _tskitr_ts_num_populations(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_populations(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_migrations
int ts_num_migrations(SEXP ts);
RcppExport SEXP _tskitr_ts_num_migrations(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_migrations(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_individuals
int ts_num_individuals(SEXP ts);
RcppExport SEXP _tskitr_ts_num_individuals(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_individuals(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_samples
int ts_num_samples(SEXP ts);
RcppExport SEXP _tskitr_ts_num_samples(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_samples(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_nodes
int ts_num_nodes(SEXP ts);
RcppExport SEXP _tskitr_ts_num_nodes(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_nodes(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_edges
int ts_num_edges(SEXP ts);
RcppExport SEXP _tskitr_ts_num_edges(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_edges(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_trees
int ts_num_trees(SEXP ts);
RcppExport SEXP _tskitr_ts_num_trees(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_trees(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_sites
int ts_num_sites(SEXP ts);
RcppExport SEXP _tskitr_ts_num_sites(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_sites(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_mutations
int ts_num_mutations(SEXP ts);
RcppExport SEXP _tskitr_ts_num_mutations(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_mutations(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_sequence_length
double ts_sequence_length(SEXP ts);
RcppExport SEXP _tskitr_ts_sequence_length(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_sequence_length(ts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tskitr_kastore_version", (DL_FUNC) &_tskitr_kastore_version, 0},
    {"_tskitr_tskit_version", (DL_FUNC) &_tskitr_tskit_version, 0},
    {"_tskitr_ts_load", (DL_FUNC) &_tskitr_ts_load, 2},
    {"_tskitr_ts_dump", (DL_FUNC) &_tskitr_ts_dump, 3},
    {"_tskitr_ts_num", (DL_FUNC) &_tskitr_ts_num, 1},
    {"_tskitr_ts_num_provenances", (DL_FUNC) &_tskitr_ts_num_provenances, 1},
    {"_tskitr_ts_num_populations", (DL_FUNC) &_tskitr_ts_num_populations, 1},
    {"_tskitr_ts_num_migrations", (DL_FUNC) &_tskitr_ts_num_migrations, 1},
    {"_tskitr_ts_num_individuals", (DL_FUNC) &_tskitr_ts_num_individuals, 1},
    {"_tskitr_ts_num_samples", (DL_FUNC) &_tskitr_ts_num_samples, 1},
    {"_tskitr_ts_num_nodes", (DL_FUNC) &_tskitr_ts_num_nodes, 1},
    {"_tskitr_ts_num_edges", (DL_FUNC) &_tskitr_ts_num_edges, 1},
    {"_tskitr_ts_num_trees", (DL_FUNC) &_tskitr_ts_num_trees, 1},
    {"_tskitr_ts_num_sites", (DL_FUNC) &_tskitr_ts_num_sites, 1},
    {"_tskitr_ts_num_mutations", (DL_FUNC) &_tskitr_ts_num_mutations, 1},
    {"_tskitr_ts_sequence_length", (DL_FUNC) &_tskitr_ts_sequence_length, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tskitr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
