// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kastore_version
Rcpp::IntegerVector kastore_version();
RcppExport SEXP _RcppTskit_kastore_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(kastore_version());
    return rcpp_result_gen;
END_RCPP
}
// tskit_version
Rcpp::IntegerVector tskit_version();
RcppExport SEXP _RcppTskit_tskit_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(tskit_version());
    return rcpp_result_gen;
END_RCPP
}
// ts_load_ptr
SEXP ts_load_ptr(const std::string file, const int options);
RcppExport SEXP _RcppTskit_ts_load_ptr(SEXP fileSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< const int >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_load_ptr(file, options));
    return rcpp_result_gen;
END_RCPP
}
// ts_dump_ptr
void ts_dump_ptr(const SEXP ts, const std::string file, const int options);
RcppExport SEXP _RcppTskit_ts_dump_ptr(SEXP tsSEXP, SEXP fileSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< const std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< const int >::type options(optionsSEXP);
    ts_dump_ptr(ts, file, options);
    return R_NilValue;
END_RCPP
}
// ts_num_provenances_ptr
int ts_num_provenances_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_provenances_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_provenances_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_populations_ptr
int ts_num_populations_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_populations_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_populations_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_migrations_ptr
int ts_num_migrations_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_migrations_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_migrations_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_individuals_ptr
int ts_num_individuals_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_individuals_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_individuals_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_samples_ptr
int ts_num_samples_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_samples_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_samples_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_nodes_ptr
int ts_num_nodes_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_nodes_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_nodes_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_edges_ptr
int ts_num_edges_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_edges_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_edges_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_trees_ptr
int ts_num_trees_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_trees_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_trees_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_sites_ptr
int ts_num_sites_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_sites_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_sites_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_num_mutations_ptr
int ts_num_mutations_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_num_mutations_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_num_mutations_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_sequence_length_ptr
double ts_sequence_length_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_sequence_length_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_sequence_length_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_time_units_ptr
Rcpp::String ts_time_units_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_time_units_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_time_units_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_min_time_ptr
double ts_min_time_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_min_time_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_min_time_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_max_time_ptr
double ts_max_time_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_max_time_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_max_time_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_summary_ptr
Rcpp::List ts_summary_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_summary_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_summary_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// ts_metadata_length_ptr
Rcpp::List ts_metadata_length_ptr(const SEXP ts);
RcppExport SEXP _RcppTskit_ts_metadata_length_ptr(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(ts_metadata_length_ptr(ts));
    return rcpp_result_gen;
END_RCPP
}
// test_tsk_bug_assert_c
void test_tsk_bug_assert_c();
RcppExport SEXP _RcppTskit_test_tsk_bug_assert_c() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_tsk_bug_assert_c();
    return R_NilValue;
END_RCPP
}
// test_tsk_bug_assert_cpp
void test_tsk_bug_assert_cpp();
RcppExport SEXP _RcppTskit_test_tsk_bug_assert_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_tsk_bug_assert_cpp();
    return R_NilValue;
END_RCPP
}
// test_tsk_trace_error_c
void test_tsk_trace_error_c();
RcppExport SEXP _RcppTskit_test_tsk_trace_error_c() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_tsk_trace_error_c();
    return R_NilValue;
END_RCPP
}
// test_tsk_trace_error_cpp
void test_tsk_trace_error_cpp();
RcppExport SEXP _RcppTskit_test_tsk_trace_error_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_tsk_trace_error_cpp();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppTskit_kastore_version", (DL_FUNC) &_RcppTskit_kastore_version, 0},
    {"_RcppTskit_tskit_version", (DL_FUNC) &_RcppTskit_tskit_version, 0},
    {"_RcppTskit_ts_load_ptr", (DL_FUNC) &_RcppTskit_ts_load_ptr, 2},
    {"_RcppTskit_ts_dump_ptr", (DL_FUNC) &_RcppTskit_ts_dump_ptr, 3},
    {"_RcppTskit_ts_num_provenances_ptr", (DL_FUNC) &_RcppTskit_ts_num_provenances_ptr, 1},
    {"_RcppTskit_ts_num_populations_ptr", (DL_FUNC) &_RcppTskit_ts_num_populations_ptr, 1},
    {"_RcppTskit_ts_num_migrations_ptr", (DL_FUNC) &_RcppTskit_ts_num_migrations_ptr, 1},
    {"_RcppTskit_ts_num_individuals_ptr", (DL_FUNC) &_RcppTskit_ts_num_individuals_ptr, 1},
    {"_RcppTskit_ts_num_samples_ptr", (DL_FUNC) &_RcppTskit_ts_num_samples_ptr, 1},
    {"_RcppTskit_ts_num_nodes_ptr", (DL_FUNC) &_RcppTskit_ts_num_nodes_ptr, 1},
    {"_RcppTskit_ts_num_edges_ptr", (DL_FUNC) &_RcppTskit_ts_num_edges_ptr, 1},
    {"_RcppTskit_ts_num_trees_ptr", (DL_FUNC) &_RcppTskit_ts_num_trees_ptr, 1},
    {"_RcppTskit_ts_num_sites_ptr", (DL_FUNC) &_RcppTskit_ts_num_sites_ptr, 1},
    {"_RcppTskit_ts_num_mutations_ptr", (DL_FUNC) &_RcppTskit_ts_num_mutations_ptr, 1},
    {"_RcppTskit_ts_sequence_length_ptr", (DL_FUNC) &_RcppTskit_ts_sequence_length_ptr, 1},
    {"_RcppTskit_ts_time_units_ptr", (DL_FUNC) &_RcppTskit_ts_time_units_ptr, 1},
    {"_RcppTskit_ts_min_time_ptr", (DL_FUNC) &_RcppTskit_ts_min_time_ptr, 1},
    {"_RcppTskit_ts_max_time_ptr", (DL_FUNC) &_RcppTskit_ts_max_time_ptr, 1},
    {"_RcppTskit_ts_summary_ptr", (DL_FUNC) &_RcppTskit_ts_summary_ptr, 1},
    {"_RcppTskit_ts_metadata_length_ptr", (DL_FUNC) &_RcppTskit_ts_metadata_length_ptr, 1},
    {"_RcppTskit_test_tsk_bug_assert_c", (DL_FUNC) &_RcppTskit_test_tsk_bug_assert_c, 0},
    {"_RcppTskit_test_tsk_bug_assert_cpp", (DL_FUNC) &_RcppTskit_test_tsk_bug_assert_cpp, 0},
    {"_RcppTskit_test_tsk_trace_error_c", (DL_FUNC) &_RcppTskit_test_tsk_trace_error_c, 0},
    {"_RcppTskit_test_tsk_trace_error_cpp", (DL_FUNC) &_RcppTskit_test_tsk_trace_error_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppTskit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
