# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_tskitr_rcpp_hello_world`)
}

tskit_version_major <- function() {
    .Call(`_tskitr_tskit_version_major`)
}

tskit_table_collection_init_ok <- function() {
    .Call(`_tskitr_tskit_table_collection_init_ok`)
}

