# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ts_num
#' @title Get the number of records in a tree sequence
#' @details These functions return the number of various items in a tree
#'     sequence, including provenances, populations, migrations, individuals,
#'     samples, nodes, edges, trees, sites, and mutations.
#' @param ts an external pointer to a \code{tsk_treeseq_t} object.
#' @return \code{ts_num} returns a named list with the numbers of each item,
NULL

#' Report the version of kastore C API
#'
#' @details The version is defined by kastore in the header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_tskitr_kastore_version`)
}

#' Report the version of tskit C API
#'
#' @details The version is defined by tskit in the header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_tskitr_tskit_version`)
}

#' Load tree sequence from a file
#'
#' @param file a string specifying the full path of the tree sequence file.
#' @return An external pointer to a \code{tsk_treeseq_t} object.
#' @examples
#' ts_file <- system.file("examples", "test.trees", package = "tskitr")
#' ts <- ts_load(ts_file)
#' ts
#' is(ts)
#' ts_num_nodes(ts)
#' @export
ts_load <- function(file) {
    .Call(`_tskitr_ts_load`, file)
}

#' @examples
#' ts_file <- system.file("examples", "test.trees", package = "tskitr")
#' ts <- ts_load(ts_file)
#' ts_num(ts)
#' ts_num_provenances(ts)
#' ts_num_populations(ts)
#' ts_num_migrations(ts)
#' ts_num_individuals(ts)
#' ts_num_samples(ts)
#' ts_num_nodes(ts)
#' ts_num_edges(ts)
#' ts_num_trees(ts)
#' ts_num_sites(ts)
#' ts_num_mutations(ts)
#' @export
ts_num <- function(ts) {
    .Call(`_tskitr_ts_num`, ts)
}

#' @describeIn ts_num Get the number of provenances in a tree sequence
#' @export
ts_num_provenances <- function(ts) {
    .Call(`_tskitr_ts_num_provenances`, ts)
}

#' @describeIn ts_num Get the number of populations in a tree sequence
#' @export
ts_num_populations <- function(ts) {
    .Call(`_tskitr_ts_num_populations`, ts)
}

#' @describeIn ts_num Get the number of migrations in a tree sequence
#' @export
ts_num_migrations <- function(ts) {
    .Call(`_tskitr_ts_num_migrations`, ts)
}

#' @describeIn ts_num Get the number of individuals in a tree sequence
#' @export
ts_num_individuals <- function(ts) {
    .Call(`_tskitr_ts_num_individuals`, ts)
}

#' @describeIn ts_num Get the number of samples in a tree sequence
#' @export
ts_num_samples <- function(ts) {
    .Call(`_tskitr_ts_num_samples`, ts)
}

#' @describeIn ts_num Get the number of nodes in a tree sequence
#' @export
ts_num_nodes <- function(ts) {
    .Call(`_tskitr_ts_num_nodes`, ts)
}

#' @describeIn ts_num Get the number of edges in a tree sequence
#' @export
ts_num_edges <- function(ts) {
    .Call(`_tskitr_ts_num_edges`, ts)
}

#' @describeIn ts_num Get the number of trees in a tree sequence
#' @export
ts_num_trees <- function(ts) {
    .Call(`_tskitr_ts_num_trees`, ts)
}

#' @describeIn ts_num Get the number of sites in a tree sequence
#' @export
ts_num_sites <- function(ts) {
    .Call(`_tskitr_ts_num_sites`, ts)
}

#' @describeIn ts_num Get the number of mutations in a tree sequence
#' @export
ts_num_mutations <- function(ts) {
    .Call(`_tskitr_ts_num_mutations`, ts)
}

