# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_tskitr_rcpp_hello_world`)
}

tskit_version_major <- function() {
    .Call(`_tskitr_tskit_version_major`)
}

tskit_table_collection_init_ok <- function() {
    .Call(`_tskitr_tskit_table_collection_init_ok`)
}

tskit_table_collection_num_nodes_zero <- function() {
    .Call(`_tskitr_tskit_table_collection_num_nodes_zero`)
}

tskit_treeseq_num_nodes_from_file <- function(file) {
    .Call(`_tskitr_tskit_treeseq_num_nodes_from_file`, file)
}

tskit_treeseq_load_xptr <- function(file) {
    .Call(`_tskitr_tskit_treeseq_load_xptr`, file)
}

tskit_treeseq_num_nodes <- function(xp) {
    .Call(`_tskitr_tskit_treeseq_num_nodes`, xp)
}

