# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_tskitr_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_tskitr_test_tsk_bug_assert_cpp`))
}

#' Report the version of installed kastore C API
#'
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_tskitr_kastore_version`)
}

#' Report the version of installed tskit C API
#'
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_tskitr_tskit_version`)
}

#' Load a tree sequence from a file.
#'
#' @param file a string specifying the full path of the tree sequence file.
#' @param options integer bitwise options (see details).
#' @details This function calls \code{tsk_treeseq_load()} from the tskit C API.
#'   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_load}
#'   provides more details.
#' @return Tree sequence as an external pointer to a \code{tsk_treeseq_t}
#'   object.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts
#' is(ts)
#' ts_num_nodes(ts)
#' @export
ts_load <- function(file, options = 0L) {
    .Call(`_tskitr_ts_load`, file, options)
}

#' Write a tree sequence to file.
#'
#' @param ts tree sequence as an external pointer to a \code{tsk_treeseq_t}
#'   object.
#' @param file a string specifying the full path of the tree sequence file
#' @param options integer bitwise options (see details).
#' @details This function calls \code{tsk_treeseq_dump()} from the tskit C API
#'   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_dump}
#'   provides more details.
#' @return No return value, called for side effects.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts
#' dump_file <- tempfile()
#' ts_dump(ts, dump_file)
#' @export
ts_dump <- function(ts, file, options = 0L) {
    invisible(.Call(`_tskitr_ts_dump`, ts, file, options))
}

#' @name ts_summary
#' @title Get the summary of properties and number of records in a tree
#'   sequence
#' @param ts tree sequence as an external pointer to a \code{tsk_treeseq_t}
#'   object.
#' @details These functions return the summary of properties and number of
#'   records in a tree sequence, by calling
#'   \code{tsk_treeseq_get_num_provenances()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_provenances},
#'   \code{tsk_treeseq_get_num_populations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_populations},
#'   \code{tsk_treeseq_get_num_migrations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_migrations},
#'   \code{tsk_treeseq_get_num_individuals()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_individuals},
#'   \code{tsk_treeseq_get_num_samples()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_samples},
#'   \code{tsk_treeseq_get_num_nodes()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_nodes},
#'   \code{tsk_treeseq_get_num_edges()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_edges},
#'   \code{tsk_treeseq_get_num_trees()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_trees},
#'   \code{tsk_treeseq_get_num_sites()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_sites},
#'   \code{tsk_treeseq_get_num_mutations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_mutations},
#'   \code{tsk_treeseq_get_sequence_length()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_sequence_length},
#'   and
#'   \code{tsk_treeseq_get_time_units()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_time_units}.
#'   from the tskit C API. See the linked documentation for more details.
#' @return \code{ts_summary} returns a named list with the number/value for
#'   all items, while other functions \code{ts_num_x} etc. return the
#'   number/value of each item.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts_summary(ts)
#' ts_num_provenances(ts)
#' ts_num_populations(ts)
#' ts_num_migrations(ts)
#' ts_num_individuals(ts)
#' ts_num_samples(ts)
#' ts_num_nodes(ts)
#' ts_num_edges(ts)
#' ts_num_trees(ts)
#' ts_num_sites(ts)
#' ts_num_mutations(ts)
#' ts_sequence_length(ts)
#' ts_time_units(ts)
#' @export
ts_summary <- function(ts) {
    .Call(`_tskitr_ts_summary`, ts)
}

#' @describeIn ts_summary Get the number of provenances in a tree sequence
#' @export
ts_num_provenances <- function(ts) {
    .Call(`_tskitr_ts_num_provenances`, ts)
}

#' @describeIn ts_summary Get the number of populations in a tree sequence
#' @export
ts_num_populations <- function(ts) {
    .Call(`_tskitr_ts_num_populations`, ts)
}

#' @describeIn ts_summary Get the number of migrations in a tree sequence
#' @export
ts_num_migrations <- function(ts) {
    .Call(`_tskitr_ts_num_migrations`, ts)
}

#' @describeIn ts_summary Get the number of individuals in a tree sequence
#' @export
ts_num_individuals <- function(ts) {
    .Call(`_tskitr_ts_num_individuals`, ts)
}

#' @describeIn ts_summary Get the number of samples (of nodes) in a tree
#'   sequence
#' @export
ts_num_samples <- function(ts) {
    .Call(`_tskitr_ts_num_samples`, ts)
}

#' @describeIn ts_summary Get the number of nodes in a tree sequence
#' @export
ts_num_nodes <- function(ts) {
    .Call(`_tskitr_ts_num_nodes`, ts)
}

#' @describeIn ts_summary Get the number of edges in a tree sequence
#' @export
ts_num_edges <- function(ts) {
    .Call(`_tskitr_ts_num_edges`, ts)
}

#' @describeIn ts_summary Get the number of trees in a tree sequence
#' @export
ts_num_trees <- function(ts) {
    .Call(`_tskitr_ts_num_trees`, ts)
}

#' @describeIn ts_summary Get the number of sites in a tree sequence
#' @export
ts_num_sites <- function(ts) {
    .Call(`_tskitr_ts_num_sites`, ts)
}

#' @describeIn ts_summary Get the number of mutations in a tree sequence
#' @export
ts_num_mutations <- function(ts) {
    .Call(`_tskitr_ts_num_mutations`, ts)
}

#' @describeIn ts_summary Get the sequence length
#' @export
ts_sequence_length <- function(ts) {
    .Call(`_tskitr_ts_sequence_length`, ts)
}

#' @describeIn ts_summary Get the time units string
#' @export
ts_time_units <- function(ts) {
    .Call(`_tskitr_ts_time_units`, ts)
}

#' @name ts_metadata_length
#' @title Get the length of metadata in a tree sequence and its tables
#' @param ts tree sequence as an external pointer to a \code{tsk_treeseq_t}
#'   object.
#' @details This function returns the length of metadata stored on the tree
#'   sequence and in each table by calling
#'   \code{tsk_treeseq_get_metadata_length()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_metadata_length}
#'   on tree sequence and
#'   \code{ts->tables->x->metadata_length} on each table \code{x}, e.g.,
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_population_table_t.metadata_length},
#'   from the tskit C API. See the linked documentation for more details.
#' @return A named list with the length of metadata.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts_metadata_length(ts)
#' @export
ts_metadata_length <- function(ts) {
    .Call(`_tskitr_ts_metadata_length`, ts)
}

