# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Finalizer function to free tsk_treeseq_t when it is garbage collected
#'
#' @param xptr_sexp an external pointer to a \code{tsk_treeseq_t} object.
#' @details Frees memory allocated to a \code{tsk_treeseq_t} object and deletes
#'   its pointer by calling \code{tsk_treeseq_free()} from the tskit C API.
#'   See \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_free}
#'   for more details.
NULL

#' Report the version of installed kastore C API
#'
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_tskitr_kastore_version`)
}

#' Report the version of installed tskit C API
#'
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'     \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_tskitr_tskit_version`)
}

#' Load a tree sequence from a file.
#'
#' @param file a string specifying the full path of the tree sequence file.
#' @param options integer bitwise options (see details).
#' @return An external pointer to a \code{tsk_treeseq_t} object.
#' @details This function calls \code{tsk_treeseq_load()} from the tskit C API.
#'   See \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_load}
#'   for more details.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts
#' is(ts)
#' ts_num_nodes(ts)
#' @export
ts_load <- function(file, options = 0L) {
    .Call(`_tskitr_ts_load`, file, options)
}

#' Write a tree sequence to file.
#'
#' @param ts an external pointer to a \code{tsk_treeseq_t} object.
#' @param file a string specifying the full path of the tree sequence file.
#' @param options integer bitwise options (see details).
#' @details This function calls \code{tsk_treeseq_dump()} from the tskit C API
#'   See \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_dump}
#'   for more details.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts
#' dump_file <- tempfile()
#' ts_dump(ts, dump_file)
#' @export
ts_dump <- function(ts, file, options = 0L) {
    invisible(.Call(`_tskitr_ts_dump`, ts, file, options))
}

#' @name ts_num
#' @title Get the number of records in a tree sequence
#' @details These functions return the number of various items in a tree
#'     sequence, including provenances, populations, migrations, individuals,
#'     samples, nodes, edges, trees, sites, and mutations.
#' @param ts an external pointer to a \code{tsk_treeseq_t} object.
#' @details These functions call
#'   \code{tsk_treeseq_get_num_provenances()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_provenances},
#'   \code{tsk_treeseq_get_num_populations()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_populations},
#'   \code{tsk_treeseq_get_num_migrations()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_migrations},
#'   \code{tsk_treeseq_get_num_individuals()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_individuals},
#'   \code{tsk_treeseq_get_num_samples()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_samples},
#'   \code{tsk_treeseq_get_num_nodes()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_nodes},
#'   \code{tsk_treeseq_get_num_edges()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_edges},
#'   \code{tsk_treeseq_get_num_trees()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_trees},
#'   \code{tsk_treeseq_get_num_sites()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_sites},
#'   \code{tsk_treeseq_get_num_mutations()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_mutations},
#'   and
#'   \code{tsk_treeseq_get_sequence_length()} \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_sequence_length}
#'   from the tskit C API. See the linked documentation for more details.
#' @return \code{ts_num} returns a named list with the numbers of each item,
#'     while \code{ts_num_x} return the number of each item. All numbers are
#'     returned as integers.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "tskitr")
#' ts <- tskitr::ts_load(ts_file) # slendr also has ts_load()!
#' ts_num(ts)
#' ts_num_provenances(ts)
#' ts_num_populations(ts)
#' ts_num_migrations(ts)
#' ts_num_individuals(ts)
#' ts_num_samples(ts)
#' ts_num_nodes(ts)
#' ts_num_edges(ts)
#' ts_num_trees(ts)
#' ts_num_sites(ts)
#' ts_num_mutations(ts)
#' ts_sequence_length(ts)
#' @export
ts_num <- function(ts) {
    .Call(`_tskitr_ts_num`, ts)
}

#' @describeIn ts_num Get the number of provenances in a tree sequence
#' @export
ts_num_provenances <- function(ts) {
    .Call(`_tskitr_ts_num_provenances`, ts)
}

#' @describeIn ts_num Get the number of populations in a tree sequence
#' @export
ts_num_populations <- function(ts) {
    .Call(`_tskitr_ts_num_populations`, ts)
}

#' @describeIn ts_num Get the number of migrations in a tree sequence
#' @export
ts_num_migrations <- function(ts) {
    .Call(`_tskitr_ts_num_migrations`, ts)
}

#' @describeIn ts_num Get the number of individuals in a tree sequence
#' @export
ts_num_individuals <- function(ts) {
    .Call(`_tskitr_ts_num_individuals`, ts)
}

#' @describeIn ts_num Get the number of samples in a tree sequence
#' @export
ts_num_samples <- function(ts) {
    .Call(`_tskitr_ts_num_samples`, ts)
}

#' @describeIn ts_num Get the number of nodes in a tree sequence
#' @export
ts_num_nodes <- function(ts) {
    .Call(`_tskitr_ts_num_nodes`, ts)
}

#' @describeIn ts_num Get the number of edges in a tree sequence
#' @export
ts_num_edges <- function(ts) {
    .Call(`_tskitr_ts_num_edges`, ts)
}

#' @describeIn ts_num Get the number of trees in a tree sequence
#' @export
ts_num_trees <- function(ts) {
    .Call(`_tskitr_ts_num_trees`, ts)
}

#' @describeIn ts_num Get the number of sites in a tree sequence
#' @export
ts_num_sites <- function(ts) {
    .Call(`_tskitr_ts_num_sites`, ts)
}

#' @describeIn ts_num Get the number of mutations in a tree sequence
#' @export
ts_num_mutations <- function(ts) {
    .Call(`_tskitr_ts_num_mutations`, ts)
}

#' @describeIn ts_num Get the sequence length
#' @export
ts_sequence_length <- function(ts) {
    .Call(`_tskitr_ts_sequence_length`, ts)
}

