# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Report the version of installed kastore C API
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_RcppTskit_kastore_version`)
}

#' @title Report the version of installed \code{tskit} C API
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_RcppTskit_tskit_version`)
}

ts_ptr_load <- function(file, options = 0L) {
    .Call(`_RcppTskit_ts_ptr_load`, file, options)
}

tc_ptr_load <- function(file, options = 0L) {
    .Call(`_RcppTskit_tc_ptr_load`, file, options)
}

ts_ptr_dump <- function(ts, file, options = 0L) {
    invisible(.Call(`_RcppTskit_ts_ptr_dump`, ts, file, options))
}

tc_ptr_dump <- function(tc, file, options = 0L) {
    invisible(.Call(`_RcppTskit_tc_ptr_dump`, tc, file, options))
}

ts_ptr_to_tc_ptr <- function(ts, options = 0L) {
    .Call(`_RcppTskit_ts_ptr_to_tc_ptr`, ts, options)
}

tc_ptr_to_ts_ptr <- function(tc, options = 0L) {
    .Call(`_RcppTskit_tc_ptr_to_ts_ptr`, tc, options)
}

ts_ptr_num_provenances <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_provenances`, ts)
}

ts_ptr_num_populations <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_populations`, ts)
}

ts_ptr_num_migrations <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_migrations`, ts)
}

ts_ptr_num_individuals <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_individuals`, ts)
}

ts_ptr_num_samples <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_samples`, ts)
}

ts_ptr_num_nodes <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_nodes`, ts)
}

ts_ptr_num_edges <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_edges`, ts)
}

ts_ptr_num_trees <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_trees`, ts)
}

ts_ptr_num_sites <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_sites`, ts)
}

ts_ptr_num_mutations <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_num_mutations`, ts)
}

ts_ptr_sequence_length <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_sequence_length`, ts)
}

ts_ptr_time_units <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_time_units`, ts)
}

ts_ptr_min_time <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_min_time`, ts)
}

ts_ptr_max_time <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_max_time`, ts)
}

ts_ptr_summary <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_summary`, ts)
}

tc_ptr_summary <- function(tc) {
    .Call(`_RcppTskit_tc_ptr_summary`, tc)
}

ts_ptr_metadata_length <- function(ts) {
    .Call(`_RcppTskit_ts_ptr_metadata_length`, ts)
}

tc_ptr_metadata_length <- function(tc) {
    .Call(`_RcppTskit_tc_ptr_metadata_length`, tc)
}

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_cpp`))
}

test_tsk_trace_error_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_c`))
}

test_tsk_trace_error_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_cpp`))
}

tsk_trace_errors_defined <- function() {
    .Call(`_RcppTskit_tsk_trace_errors_defined`)
}

test_ts_ptr_to_tc_ptr_forced_error <- function(ts) {
    .Call(`_RcppTskit_test_ts_ptr_to_tc_ptr_forced_error`, ts)
}

test_tc_ptr_to_ts_ptr_forced_error <- function(tc) {
    .Call(`_RcppTskit_test_tc_ptr_to_ts_ptr_forced_error`, tc)
}

