# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Report the version of installed kastore C API
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_RcppTskit_kastore_version`)
}

#' @title Report the version of installed tskit C API
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_RcppTskit_tskit_version`)
}

#' @name ts_load_ptr
#' @title Load a tree sequence from a file
#' @param file a string specifying the full path of the tree sequence file.
#' @param options integer bitwise options (see details).
#' @details This function calls tskit C API: \code{tsk_treeseq_load()}
#'   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_load}.
#' @return \code{ts_load()} returns a \code{\link{TreeSequence}} object.
#'  \code{ts_load_ptr()} returns external pointer to tree sequence as a
#'  \code{tsk_treeseq_t} object.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "RcppTskit")
#'
#' # TreeSequence class object
#' ts <- ts_load(ts_file)
#' is(ts)
#' ts
#' ts$num_nodes()
#'
#' # External pointer object
#' ts_ptr <- ts_load_ptr(ts_file)
#' is(ts_ptr)
#' ts_ptr
#' ts_num_nodes_ptr(ts_ptr)
#'
#' # Also
#' ts <- TreeSequence$new(file = ts_file); is(ts)
#' ts <- TreeSequence$new(pointer = ts_ptr); is(ts)
#' @export
ts_load_ptr <- function(file, options = 0L) {
    .Call(`_RcppTskit_ts_load_ptr`, file, options)
}

#' @name ts_dump_ptr
#' @title Write a tree sequence to a file
#' @param ts tree sequence as a \code{\link{TreeSequence}} object or
#'   an external pointer to tree sequence as a \code{tsk_treeseq_t} object.
#' @param file a string specifying the full path of the tree sequence file
#' @param options integer bitwise options (see details).
#' @details This function calls the tskit C API: \code{tsk_treeseq_dump()}
#'   \url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_dump}.
#' @return No return value; called for side effects.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "RcppTskit")
#'
#' # TreeSequence class object
#' ts <- ts_load(ts_file)
#' dump_file <- tempfile()
#' ts$dump(dump_file)
#'
#' # External pointer object
#' ts_ptr <- ts$pointer
#' ts_dump_ptr(ts_ptr, dump_file)
#' \dontshow{on.exit(file.remove(dump_file)) # clean up}
#' @export
ts_dump_ptr <- function(ts, file, options = 0L) {
    invisible(.Call(`_RcppTskit_ts_dump_ptr`, ts, file, options))
}

#' @describeIn ts_summary_ptr Get the number of provenances in a tree sequence
#' @export
ts_num_provenances_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_provenances_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of populations in a tree sequence
#' @export
ts_num_populations_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_populations_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of migrations in a tree sequence
#' @export
ts_num_migrations_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_migrations_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of individuals in a tree sequence
#' @export
ts_num_individuals_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_individuals_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of samples (of nodes) in a tree
#'   sequence
#' @export
ts_num_samples_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_samples_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of nodes in a tree sequence
#' @export
ts_num_nodes_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_nodes_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of edges in a tree sequence
#' @export
ts_num_edges_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_edges_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of trees in a tree sequence
#' @export
ts_num_trees_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_trees_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of sites in a tree sequence
#' @export
ts_num_sites_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_sites_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the number of mutations in a tree sequence
#' @export
ts_num_mutations_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_num_mutations_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the sequence length
#' @export
ts_sequence_length_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_sequence_length_ptr`, ts)
}

#' @describeIn ts_summary_ptr Get the time units string
#' @export
ts_time_units_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_time_units_ptr`, ts)
}

#' @name ts_summary_ptr
#' @title Summary of properties and number of records in a tree sequence
#' @param ts tree sequence as a \code{\link{TreeSequence}} object or
#'   an external pointer to tree sequence as a \code{tsk_treeseq_t} object.
#' @details These functions return the summary of properties and number of
#'   records in a tree sequence, by calling tskit C API:
#'   \code{tsk_treeseq_get_num_provenances()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_provenances},
#'   \code{tsk_treeseq_get_num_populations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_populations},
#'   \code{tsk_treeseq_get_num_migrations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_migrations},
#'   \code{tsk_treeseq_get_num_individuals()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_individuals},
#'   \code{tsk_treeseq_get_num_samples()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_samples},
#'   \code{tsk_treeseq_get_num_nodes()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_nodes},
#'   \code{tsk_treeseq_get_num_edges()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_edges},
#'   \code{tsk_treeseq_get_num_trees()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_trees},
#'   \code{tsk_treeseq_get_num_sites()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_sites},
#'   \code{tsk_treeseq_get_num_mutations()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_num_mutations},
#'   \code{tsk_treeseq_get_sequence_length()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_sequence_length},
#'   and
#'   \code{tsk_treeseq_get_time_units()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_time_units}.
#' @return \code{ts_summary()} and \code{ts_summary_ptr()} return
#'   a named list with the number/value for all items,
#'   while other functions \code{ts_num_x()} and \code{ts_num_x_ptr()} etc.
#'   return the number/value of each item.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "RcppTskit")
#'
#' # TreeSequence class object
#' ts <- ts_load(ts_file)
#' ts$print()
#' ts$summary()
#' ts$num_provenances()
#' ts$num_populations()
#' ts$num_migrations()
#' ts$num_individuals()
#' ts$num_samples()
#' ts$num_nodes()
#' ts$num_edges()
#' ts$num_trees()
#' ts$num_sites()
#' ts$num_mutations()
#' ts$sequence_length()
#' ts$time_units()
#'
#' # External pointer object
#' ts_ptr <- ts$pointer
#' ts_summary_ptr(ts_ptr)
#' ts_num_provenances_ptr(ts_ptr)
#' ts_num_populations_ptr(ts_ptr)
#' ts_num_migrations_ptr(ts_ptr)
#' ts_num_individuals_ptr(ts_ptr)
#' ts_num_samples_ptr(ts_ptr)
#' ts_num_nodes_ptr(ts_ptr)
#' ts_num_edges_ptr(ts_ptr)
#' ts_num_trees_ptr(ts_ptr)
#' ts_num_sites_ptr(ts_ptr)
#' ts_num_mutations_ptr(ts_ptr)
#' ts_sequence_length_ptr(ts_ptr)
#' ts_time_units_ptr(ts_ptr)
#' @export
ts_summary_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_summary_ptr`, ts)
}

#' @name ts_metadata_length
#' @title Get the length of metadata in a tree sequence and its tables
#' @param ts tree sequence as a \code{\link{TreeSequence}} object or
#'   an external pointer to tree sequence as a \code{tsk_treeseq_t} object.
#' @details This function returns the length of metadata stored on the tree
#'   sequence and in each table by calling tskit C API:
#'   \code{tsk_treeseq_get_metadata_length()}
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_treeseq_get_metadata_length}
#'   on tree sequence and
#'   \code{ts->tables->x->metadata_length} on each table \code{x}, e.g.,
#'\url{https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_population_table_t.metadata_length}.
#' @return A named list with the length of metadata.
#' @examples
#' ts_file <- system.file("examples/test.trees", package = "RcppTskit")
#'
#' # TreeSequence class object
#' ts <- ts_load(ts_file)
#' ts$metadata_length()
#'
#' # External pointer object
#' ts_ptr <- ts$pointer
#' ts_metadata_length_ptr(ts_ptr)
#' @export
ts_metadata_length_ptr <- function(ts) {
    .Call(`_RcppTskit_ts_metadata_length_ptr`, ts)
}

ts_grow <- function(ts) {
    .Call(`_RcppTskit_ts_grow`, ts)
}

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_cpp`))
}

test_tsk_trace_error_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_c`))
}

test_tsk_trace_error_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_cpp`))
}

