# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Report the version of installed kastore C API
#' @details The version is stored in the installed header \code{kastore.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' kastore_version()
#' @export
kastore_version <- function() {
    .Call(`_RcppTskit_kastore_version`)
}

#' @title Report the version of installed \code{tskit} C API
#' @details The version is defined in the installed header \code{tskit/core.h}.
#' @return A named vector with three elements \code{major}, \code{minor}, and
#'   \code{patch}.
#' @examples
#' tskit_version()
#' @export
tskit_version <- function() {
    .Call(`_RcppTskit_tskit_version`)
}

ts_xptr_load <- function(file, options = 0L) {
    .Call(`_RcppTskit_ts_xptr_load`, file, options)
}

tc_xptr_load <- function(file, options = 0L) {
    .Call(`_RcppTskit_tc_xptr_load`, file, options)
}

ts_xptr_dump <- function(ts, file, options = 0L) {
    invisible(.Call(`_RcppTskit_ts_xptr_dump`, ts, file, options))
}

tc_xptr_dump <- function(tc, file, options = 0L) {
    invisible(.Call(`_RcppTskit_tc_xptr_dump`, tc, file, options))
}

ts_xptr_to_tc_xptr <- function(ts, options = 0L) {
    .Call(`_RcppTskit_ts_xptr_to_tc_xptr`, ts, options)
}

tc_xptr_to_ts_xptr <- function(tc, options = 0L) {
    .Call(`_RcppTskit_tc_xptr_to_ts_xptr`, tc, options)
}

ts_xptr_num_provenances <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_provenances`, ts)
}

ts_xptr_num_populations <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_populations`, ts)
}

ts_xptr_num_migrations <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_migrations`, ts)
}

ts_xptr_num_individuals <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_individuals`, ts)
}

ts_xptr_num_samples <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_samples`, ts)
}

ts_xptr_num_nodes <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_nodes`, ts)
}

ts_xptr_num_edges <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_edges`, ts)
}

ts_xptr_num_trees <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_trees`, ts)
}

ts_xptr_num_sites <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_sites`, ts)
}

ts_xptr_num_mutations <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_num_mutations`, ts)
}

ts_xptr_sequence_length <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_sequence_length`, ts)
}

ts_xptr_discrete_genome <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_discrete_genome`, ts)
}

ts_xptr_has_reference_sequence <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_has_reference_sequence`, ts)
}

ts_xptr_time_units <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_time_units`, ts)
}

ts_xptr_discrete_time <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_discrete_time`, ts)
}

ts_xptr_min_time <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_min_time`, ts)
}

ts_xptr_max_time <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_max_time`, ts)
}

ts_xptr_file_uuid <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_file_uuid`, ts)
}

ts_xptr_summary <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_summary`, ts)
}

ts_xptr_metadata_length <- function(ts) {
    .Call(`_RcppTskit_ts_xptr_metadata_length`, ts)
}

tc_xptr_sequence_length <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_sequence_length`, tc)
}

tc_xptr_has_reference_sequence <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_has_reference_sequence`, tc)
}

tc_xptr_time_units <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_time_units`, tc)
}

tc_xptr_file_uuid <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_file_uuid`, tc)
}

tc_xptr_has_index <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_has_index`, tc)
}

tc_xptr_summary <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_summary`, tc)
}

tc_xptr_metadata_length <- function(tc) {
    .Call(`_RcppTskit_tc_xptr_metadata_length`, tc)
}

test_tsk_bug_assert_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_c`))
}

test_tsk_bug_assert_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_bug_assert_cpp`))
}

test_tsk_trace_error_c <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_c`))
}

test_tsk_trace_error_cpp <- function() {
    invisible(.Call(`_RcppTskit_test_tsk_trace_error_cpp`))
}

tsk_trace_errors_defined <- function() {
    .Call(`_RcppTskit_tsk_trace_errors_defined`)
}

test_ts_xptr_to_tc_xptr_forced_error <- function(ts) {
    .Call(`_RcppTskit_test_ts_xptr_to_tc_xptr_forced_error`, ts)
}

test_tc_xptr_to_ts_xptr_forced_error <- function(tc) {
    .Call(`_RcppTskit_test_tc_xptr_to_ts_xptr_forced_error`, tc)
}

